# Welcome to Serverless!
# Basic servless setup for taxes excercise with api gateway and lamda_proxy integration

service: taxes-exercise


# Serverless version 2
frameworkVersion: '2'

# Provider aws, stage dev, region eu-south-1 (Milan)
provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-south-1


# Package information
package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'

# Calculate taxes post function with the related path
functions:
  calculateTaxes:
    handler: com.claranet.controller.CalculateTaxesHandler
    events:
      - http:
          path: /taxes
          method: post
